sudo: false

language: php

php:
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache:
    directories:
        - node_modules
        - $HOME/.composer/cache/files

before_install:
    - rm -rf "$HOME/.nvm"
    - git clone https://github.com/creationix/nvm.git "$HOME/.nvm"
    - source "$HOME/.nvm/nvm.sh"
    - nvm install node
    - npm config set progress false
    - npm install -g npm
    - composer self-update

install:
    - npm install
    - composer install --prefer-source

script:
    - npm run-script lint-travis
    - composer test-travis

notifications:
    email: false

    slack:
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
        rooms:
            - secure: IMQhXmr1QHHKyO6oARTEfom9TRd6xqvvScfhCdGuxKKwuddBnxSOt21CjCXJVKQfUVZXkvZD5RZYRX71tcMguv07D7Fnobh08GnXgIElE+9GYhsySm4TMekifPBz2HIqZCrcQpNcq5ggfwxCoPMS8NUz5I3GSNqEECKqmStqymJCza5g67exakpkObs3kVLIfduiHaTBcbTGVeBcF54b4gDwBeERhJBebCTHrlNYb8JkIZOFZ2m5eLZ7Of1ujl6oflNzhGxD2X3izdsi0Q3+G63lBiO/BnIcvlOvEkyLoMqIJqjMzdJoOgOvbMDtBgn+5njHCmt0efcoYEsRdNuUZXa3MlP/RJ1X60C8Vc3/TafdOk3kMm6V40vFwTCdcMikX2iMb6JXbm1mQKO+uYim3E0gDOr4SBCwdO2pRlAlflTnDw7cmda5h1mL7cLPddAEGoT7AlUuKRNTdlkIw0V8TYmCGAv5cq7seRn3bpRdU8O2EtpGPNf51kmUILNzYkBQmq7/hF2+aSTk7J2VWySWJblBHD6MFn05ojg3jUDGDq5DkYTcTfW4I5YBIn/us/FDVebPZNryF4p89h7OvzuTaqWCOlk51lWeEU+zJoxl70ABucdoowlQug01uEyECVjOtOsq99Egfrwd013zesVcy0ndwPR5hHB0ZPj9k+t0DXk=
